### ISSUE TITLE
Portal connection error after installation.

### ISSUE THREAD

**Issue by alishir** [open-webrtc-toolkit/owt-server#18] opened 2019-03-16 03:39 UTC
I successfully installed `owt-server`, but when I try to access the `https://localhost:3004` I got following error in js console:

```
TypeError: publicationGlobal is undefined[Learn More] index.js:173:5
	onbeforeunload https://localhost:3004/scripts/index.js:173
	receiveMessage resource:///actors/BrowserTabChild.jsm:93
	wrapHandlingUserInput resource://gre/modules/E10SUtils.jsm:350
	receiveMessage resource:///actors/BrowserTabChild.jsm:92
	receiveMessage resource://gre/modules/ActorManagerChild.jsm:160

Error: Portal is not connected. owt.js:9:45710

```

**Comment by starwarfan** [comment] 2019-03-21 02:38
Hi,
Please make sure your client-javascript sample is successfully built

**Comment by alishir** [comment] 2019-03-21 05:21
@starwarfan thanks, I rebuild `owt-client-javascript` following its `README.md`, after that I issue the following command:

```
./scripts/pack.js -t all --install-module --sample-path ../owt-client-javascript/dist/samples/conference/
```

But unfortunately I got the error again. Would you please guide me how should I build sample correctly?

**Comment by starwarfan** [comment] 2019-03-22 08:47
Hi,
It seems that the client-sample is not built properly.
Can you access the internet on your develop machine? since the sample page requires some non-local resource.

**Comment by 0502lian** [comment] 2019-08-10 13:12
the same problem...

**Comment by xiandeatintel** [comment] 2019-09-09 03:07
@alishir @0502lian Have you guys resolved this issue on our side?

**Comment by alishir** [comment] 2019-09-12 04:37
@xiandeatintel I didn't try any more.

**Comment by xiandeatintel** [comment] 2019-09-19 07:03
Since we didn't reproduce it and other customers didn't report it.
Let's close it now and reopen it if it happens again anywhere else.

**Closed by xiandeatintel** 2019-09-19 07:03 UTC
